using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

// ForNetwork
using SoftGear.Strix.Unity.Runtime;

public class DaifugoTask : MonoBehaviour
{
    private static readonly string[] RANK_PREFIX_LIST = new string[]
    {
    "",
    "1st",
    "2nd",
    "3rd",
    "4th",
    };

    public DaifugoCard cardBase = null; // ã‚«ãƒ¼ãƒ‰ã®å…ƒãƒã‚¿
    public Transform centerRoot = null; // ä¸­å¤®ã«ç½®ãã‚«ãƒ¼ãƒ‰

    public GameObject passUI = null;
    public GameObject resultUI = null;
    public Text resultText = null;

    public static DaifugoTask instance = null;


    private bool isRoomOwner => StrixNetwork.instance.isRoomOwner;

    private DaifugoPlayer localPlayer => DaifugoPlayer.localPlayer;
    private int playerCount => DaifugoPlayer.playerList.Count; // ç¾åœ¨ä½•äººãƒ—ãƒ¬ã‚¤ã—ã¦ã„ã‚‹ã‹å–å¾—
    private int currenTurnIdentifier
    {
        get
        {
            return StrixNetwork.instance.room.GetState();
        }
        set
        {
            // é€ä¿¡å‡¦ç†
            var rp = new Dictionary<string, object>(); //StrixNetwork.instance.room.GetProperties(); // ãƒ«ãƒ¼ãƒ å†…ã®æƒ…å ±ã®ã‹ãŸã¾ã‚Š
            rp.Add("state", value);
            StrixNetwork.instance.SetRoom(StrixNetwork.instance.room.GetPrimaryKey(), rp, null, null);
        }
    }
   
    private int currentTurn => currenTurnIdentifier / 10;
    private int currentPlayerIndex => currenTurnIdentifier % 10;
    private DaifugoPlayer currentPlayer
    {
        get
        {
            int index = currentPlayerIndex;
            return (index < playerCount) ? DaifugoPlayer.playerList[index] : null;
        }
    }

    private bool isMyTurn => currentPlayer == localPlayer; // è‡ªåˆ†ã®ã‚¿ãƒ¼ãƒ³ã‹

    // ã‚«ãƒ¼ãƒ‰æƒ…å ±
    private List<DaifugoCard> _centerCardList = new List<DaifugoCard>(); // ä¸­å¤®ã«ã‚ã‚‹ã‚«ãƒ¼ãƒ‰
    private List<int> _topcardList = new List<int>(); // ä¸€ç•ªä¸Šã«ã‚ã‚‹ã‚«ãƒ¼ãƒ‰ã®ID
    private List<int> _selectedCardIndexList =  new List<int>(); // é¸æŠã‚«ãƒ¼ãƒ‰ã‚¤ãƒ³ãƒ‡ãƒƒã‚¯ã‚¹
    private List<int> _selectedCardList = new List<int>(); // é¸æŠã‚«ãƒ¼ãƒ‰(ç•ªå·ã€ã‚¹ãƒ¼ãƒˆ)

    // ãƒ‘ã‚¹æƒ…å ±
    private int _continuousPassCount = 0; // é€£ç¶šãƒ‘ã‚¹å›æ•°

    // ã‚³ãƒ«ãƒ¼ãƒãƒ³
    private Coroutine _turnCoroutine = null; // ã‚¿ãƒ¼ãƒ³ç”¨ã®ã‚³ãƒ«ãƒ¼ãƒãƒ³
    private bool _isTurnSuspended = false; // ã‚¿ãƒ¼ãƒ³ãŒä¸­æ–­ã•ã‚ŒãŸã‹


    void Awake()
    {
        if(StrixNetwork.instance.room == null) 
        {
            UnityEngine.SceneManagement.SceneManager.LoadScene("Title");
            return;
        }

        instance = this;
    }

    // Start is called before the first frame update
    void Start()
    {
        // å…ƒãƒã‚¿éè¡¨ç¤º
        cardBase.gameObject.SetActive(false);

        // ï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½Ìï¿½ï¿½ï¿½ï¿½ï¿½Jï¿½n
        StartCoroutine(MainProc());
    }

    // Update is called once per frame
    void Update()
    {
        
    }

    // ï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½Ìï¿½ï¿½ï¿½
    IEnumerator MainProc()
    {
        // ï¿½Ò‹@
        while (true)
        {
            if (isRoomOwner)
            {
                if (Input.GetKeyDown(KeyCode.Return))
                {
                    break;
                }
            }
            else
            {
                break;
            }

            yield return null;
        }

        // ãƒ›ã‚¹ãƒˆã®å ´åˆã¯ã‚«ãƒ¼ãƒ‰ã‚’é…ã‚‹
        if (isRoomOwner)
        {
            DealCard();
        }

        // èˆ¹å“¡ã®ã‚«ãƒ¼ãƒ‰ãŒé…ã‚‰ã‚Œã‚‹ã¾ã§å¾…æ©Ÿ
        yield return new WaitWhile(() =>
        {
            for (int i = 0; i < playerCount; i++)
            {
                if (DaifugoPlayer.playerList[i].cardCount == 0) //ã‚«ãƒ¼ãƒ‰ï¼ã€€æŒã£ã¦ãªã„
                {
                    return true; // ã¾ã é…ã‚‰ã‚Œã¦ãªã„
                }
            }
            return false; // å…¨å“¡ãŒé…ã‚‰ã‚ŒãŸ
        });

        // å¾…æ©Ÿ
        yield return new WaitForSeconds(1.0f);

        // æœ€å¾Œã®ä¸€äººã‚’æ®‹ã—ã¦ã‚«ãƒ¼ãƒ‰å‡ºã—åˆ‡ã£ãŸã‚‰çµ‚äº†
        for(int localTurn = 0; ;)
        {
            // ã‚¿ãƒ¼ãƒ³æ•°ã€ãƒ—ãƒ¬ã‚¤ãƒ¤ãƒ¼ç•ªå·ã®åŒæœŸå¾…æ©Ÿ
            yield return new WaitWhile(() =>{ return currentTurn < localTurn || currentPlayer == null; });

            // ã‚¿ãƒ¼ãƒ³
            _turnCoroutine = StartCoroutine(TurnProc());
            yield return new WaitWhile(() => {  return _turnCoroutine != null; });

            // ã‚¿ãƒ¼ãƒ³ä¸­ã«ãƒ—ãƒ¬ã‚¤ãƒ¤ãƒ¼ãŒæŠœã‘ãŸã“ã¨ã§ã€ã‚¿ãƒ¼ãƒ³ãŒä¸­æ–­ã•ã‚ŒãŸå ´åˆã¯ continue
            if(_isTurnSuspended)
            {
                _isTurnSuspended = false;
                continue; // åŒæœŸå¾…æ©Ÿã®ã¨ã“ã‚ã¾ã§æˆ»ã‚‹
            }

            yield return new WaitForSeconds(1.0f);  

            // ã±ã™ã®UI ã‚’ã‚ªãƒ•
            passUI.SetActive(false);


            
            // ãƒ—ãƒ¬ãƒ¼ä¸­ã®ãƒ—ãƒ¬ã‚¤ãƒ¤ãƒ¼æ•°ã‚’æ±‚ã‚ã‚‹
            int leftPlayingPlayerCard = 0;
            DaifugoPlayer lastLeftPlayer = null;
            for (int i = 0; i < playerCount; i++)
            {
                if (DaifugoPlayer.playerList[i].cardCount > 0)
                {
                    leftPlayingPlayerCard++;
                    lastLeftPlayer = DaifugoPlayer.playerList[i];
                }
            }
            
            // æœ€å¾Œã®ä¸€äººã«ãªã£ã¦ã„ã‚‹å ´åˆã¯çµ‚äº†
            if(leftPlayingPlayerCard <= 1)
            {
                // æœ€å¾Œã®ä¸€äººï¼ˆå¤§è²§æ°‘ï¼‰ã®é †ä½ã‚’ç¢ºå®šã•ã›ã‚‹
                if (lastLeftPlayer != null)
                { 
                    lastLeftPlayer.SetRank(DaifugoPlayer.GetNextRank()); 
                }
                break;
            }

            // é€£ç¶šãƒ‘ã‚¹è–„ã«ã‚ˆã£ã¦ãƒˆãƒƒãƒ—ã‚«ãƒ¼ãƒ‰ã‚’ãƒªã‚»ãƒƒãƒˆ
            if(_continuousPassCount >= leftPlayingPlayerCard -1)
            {
                int n = _centerCardList.Count;
                for (int i = 0; i < n; i++)
                {
                    GameObject.Destroy(_centerCardList[i].gameObject);
                }
                _centerCardList.Clear();
                _topcardList.Clear();
            }

            // ãƒ›ã‚¹ãƒˆå´ã¯ã‚¿ãƒ¼ãƒ³ã‚’é€²ã‚ã‚‹
            if(isRoomOwner)
            {
                int nextTurn = currentTurn + 1;

                int nextPlayerIndex = -1;
                for (int i = 1; i < playerCount; i++)
                {
                    int tmpIndex  = (currentPlayerIndex + i) % playerCount;
                    if (DaifugoPlayer.playerList[tmpIndex].cardCount > 0) // æ‰‹æœ­ãŒæ®‹ã£ã¦ã„ã‚‹ï¼Ÿ
                    {
                        nextPlayerIndex = tmpIndex;
                        break;
                    }
                }

                currenTurnIdentifier = nextTurn * 10 + nextPlayerIndex;
            }
            // ã‚¿ãƒ¼ãƒ³çµ‚äº†
            localTurn++;
            yield return null;
        }
        // ãƒªã‚¶ãƒ«ãƒˆç”»é¢ã‚’ã ã™
        resultUI.SetActive(true);
        resultText.text = "GAME SET!!";
        for (int i = 1; i <= playerCount; i++)
        {
            var player = DaifugoPlayer.GetPlaeyrByRank(i);
            string name = (player == null) ? string.Empty : player.strixReplicator.roomMember.GetName();
            resultText.text = $"\n{RANK_PREFIX_LIST[i]} {name}";
        }

        yield break;
    }

    // ã‚¿ãƒ¼ãƒ³å‡¦ç†
    IEnumerator TurnProc()
    {
        // ã‚«ãƒ¼ãƒ‰é¸æŠå‡¦ç†
        yield return SelectCardProc();

        // ãƒ‘ã‚¹ã¾ãŸã¯ã‚«ãƒ¼ãƒ‰ã‚’å‡ºã™ã‹ã®åˆ†å²
        if(_selectedCardIndexList.Count == 0)
        {
            /////////// ãƒ‘ã‚¹å‡¦ç† //////////////

            // é€£ç¶šãƒ‘ã‚¹å›æ•°ã‚’åŠ ç®—
            _continuousPassCount++;

            passUI.SetActive(true);
        }
        else
        {
            ////////// ã‚«ãƒ¼ãƒ‰ã‚’å‡ºã™å‡¦ç† //////////

            // é€£ç¶šãƒ‘ã‚¹å›æ•°ã‚’ãƒªã‚»ãƒƒãƒˆ
            _continuousPassCount = 0;

            // ã‚«ãƒ¼ãƒ‰ã‚’å®Ÿéš›ã«å‡ºã™å‡¦ç†
            ShotCard();
        }

        // ã‚«ãƒ¼ãƒ‰ãŒãªããªã£ãŸã‚‰å‹åˆ©
        if (isMyTurn && currentPlayer.cardCount == 0)
        {
            currentPlayer.SetRank(DaifugoPlayer.GetNextRank()); //é †ä½ã‚»ãƒƒãƒˆ
        }

        // çµ‚äº†
        _turnCoroutine = null;
        yield break;
    }

    // ã‚«ãƒ¼ãƒ‰é¸æŠå‡¦ç†
    IEnumerator SelectCardProc()
    {
        // å…¨éƒ¨ã®ã‚«ãƒ¼ãƒ‰ã®é¸æŠã‚’è§£é™¤
        _selectedCardIndexList.Clear();
        ReflectSelectedCardList();

        if(isMyTurn)
        {
            // è‡ªåˆ†ã®ã‚¿ãƒ¼ãƒ³ //
            if(localPlayer.cardCount == 0)
            {
                // ã‚«ãƒ¼ãƒ‰æŒã£ã¦ãªã‘ã‚Œã°ãƒ‘ã‚¹

            }
            else 
            {

                while (true)
                {
                    // ã‚¯ãƒªãƒƒã‚¯åˆ¤å®š
                    if (Input.GetMouseButtonDown(0))
                    {
                        Ray ray = Camera.main.ScreenPointToRay(Input.mousePosition);
                        RaycastHit hit;
                        int hitCardIndex = -1;

                        if(Physics.Raycast(ray, out hit))
                        {
                            Debug.Log(hit.collider.gameObject.name);
                            hitCardIndex = localPlayer.IndexOfCard(hit.collider.gameObject);
                        }

                        Debug.Log(hitCardIndex);

                        if(hitCardIndex < 0)
                        {
                            // å…¨éƒ¨ã‚«ãƒ¼ãƒ‰ã‚’é¸æŠã€è§£é™¤
                            _selectedCardIndexList.Clear();
                        }
                        else
                        {
                            // ã‚«ãƒ¼ãƒ‰ã®é¸æŠã€è§£é™¤
                            if(_selectedCardIndexList.Contains(hitCardIndex))
                            {
                                _selectedCardIndexList.Remove(hitCardIndex);

                            }
                            else
                            {
                                _selectedCardIndexList.Add(hitCardIndex);
                            }
                        }
                        ReflectSelectedCardList();
                    }
                    // æ±ºå®šãƒœã‚¿ãƒ³åˆ¤å®š
                    if(Input.GetKeyDown(KeyCode.Return))
                    {
                        // ã‚«ãƒ¼ãƒ‰ã‚’å‡ºã›ã‚‹ã‹åˆ¤å®š
                        if(CheckSelectedCardPlayerble())
                        {
                            break; //å¿…ãšå‡ºã›ã‚‹çŠ¶æ…‹
                        }
                    }
                    // ã€Œãƒ‘ã‚¹ã€ãƒœã‚¿ãƒ³æ±ºå®š
                    if(Input.GetKeyDown(KeyCode.P))
                    {
                        // 
                        _selectedCardIndexList.Clear();
                        ReflectSelectedCardList();

                        break;
                    }

                    yield return null;
                }

                // RPC
                int n = _selectedCardList.Count;
                byte[] selectedCardListByte = new byte[n];
                for(int i = 0; i < n; i++)
                {
                    selectedCardListByte[i] = (byte)_selectedCardList[i];
                }
                currentPlayer.ShotCard(selectedCardListByte);
             }
        }
        else
        {
            // ä»–äººã®ã‚¿ãƒ¼ãƒ³ //
            yield return new WaitWhile(()=> { return currentPlayer.decideInfoQueue.Count == 0; });

            var val = currentPlayer.decideInfoQueue.Dequeue();

            _selectedCardList.Clear();
            int n = val.infoVelues.Length;
            for(int i = 0; i < n; i++)
            {
                int card = val.infoVelues[i];
                if(card == 0)
                {
                    break;
                }
                _selectedCardList.Add(card);
            }

        }
        yield break;
    }

    // ã‚«ãƒ¼ãƒ‰ã‚’å‡ºã™
     void ShotCard()
    {
        List<DaifugoCard> shotCardList = new List<DaifugoCard>();

        int centerCardCount = _centerCardList.Count; // ä»Šä¸­å¤®ã«ç©ã¾ã‚Œã¦ã„ã‚‹ã‚«ãƒ¼ãƒ‰ã®æšæ•°

        // ä¸€ç•ªãŠä¸Šã®ã‚«ãƒ¼ãƒ‰æ›´æ–°
        _topcardList.Clear();
        int n = _selectedCardList.Count;
        for(int i = 0; i < n;  i++)
        {
            int card = _selectedCardList[i];

            _topcardList.Add(card);

            var removeCard = currentPlayer.RemoveCard(card);
            if (removeCard != null)
             {
                removeCard.transform.SetParent(centerRoot, true);
                _centerCardList.Add(removeCard);
                shotCardList.Add(removeCard);
             }
        }

        _selectedCardIndexList.Clear();
        ReflectSelectedCardList();

        //
        float randomRotY = Random.Range(-10.0f, 10.0f);
        n =shotCardList.Count;
        for (int i = 0;i < n;i++)
        {
            float x = 0.5f * (i - (n - 1) * 0.5f) + Random.Range(-1.0f, 0.1f);
            float y = (1 + centerCardCount + i) * 0.01f;
            float z = Random.Range(-0.1f, 0.1f);
            shotCardList[i].SetDestPositionAndRotation(new Vector3(x, y, z), Quaternion.Euler(90.0f, randomRotY, 0.0f), false);
        }

        currentPlayer.SetCardPositionAndRotation();
    }

    void ReflectSelectedCardList()
    {
        // ã‹ãƒ¼åº¦ã®é¸æŠä¸Šä½“ã‚’åæ˜ 
        _selectedCardList.Clear();

        foreach (var cardIndex in _selectedCardIndexList)
        {
            int card = localPlayer.cardList[cardIndex].cardIdentifier;
            _selectedCardList.Add(card);
        }

        _selectedCardList.Sort((a, b) => { return DaifugoDefine.CompareCardIdentifier(a, b); }) ; // æ˜‡é †

        currentPlayer.SetCardPositionAndRotation(false, _selectedCardIndexList);
    }

    // ã‚«ãƒ¼ãƒ‰é…ã‚‹
    void DealCard()
    {
        // å±±æœ­ã‚’ç”Ÿæˆ
        // Suit : 0 ~ 3 ï¿½iï¿½Xï¿½yï¿½[ï¿½hï¿½Aï¿½nï¿½[ï¿½gï¿½Aï¿½Nï¿½ï¿½ï¿½uï¿½Aï¿½_ï¿½Cï¿½ï¿½ï¿½j
        // Number : 1 ~ 13
        List<int> allCardList = new List<int>();
        for (int i = 1; i <= 13; i++)
        {
            for (int j = 0; j <= 3; j++)
            {
                allCardList.Add(10 * i + j);
            }
        }

        // ï¿½vï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½Æ‚ÌƒJï¿½[ï¿½hï¿½ï¿½ï¿½Xï¿½gï¿½ğ¶ï¿½
        int playerCount = DaifugoPlayer.playerList.Count;
        List<int>[] eachCardsList = new List<int>[playerCount];
        for (int i = 0; i < playerCount; i++)
        {
            eachCardsList[i] = new List<int>();
        }

        // ï¿½Jï¿½[ï¿½hï¿½ï¿½ï¿½ï¿½ï¿½ï¿½_ï¿½ï¿½ï¿½É”zï¿½z
        while (allCardList.Count > 0)
        {
            for (int i = 0; i < playerCount && allCardList.Count > 0; i++)
            {
                int index = Random.Range(0, allCardList.Count);
                eachCardsList[i].Add(allCardList[index]);
                allCardList.RemoveAt(index);
            }
        }

        // é…ã£ãŸã‚«ãƒ¼ãƒ‰ã‚’é€ä¿¡
        for (int i = 0; i < playerCount; i++)
        {
            var player = DaifugoPlayer.playerList[i];
            var cardList = eachCardsList[i];
            Debug.Log($"[Cards] {i} : {cardList.Count}");
            cardList.Sort((a, b) => { return a - b; });
            int n = cardList.Count;
            byte[] cards = new byte[n];
            for (int j = 0; j < n; j++)
            {
                cards[j] = (byte)cardList[j];
            }
            player.DealCardFromHost(cards); // RPC
        }
    }

    /// <summary>
    /// ã‚«ãƒ¼ãƒ‰ã‚’ä½œã‚‹
    /// </summary>
    /// <returns></returns>
    public DaifugoCard InstantiateCard()
    {
        cardBase.gameObject.SetActive(true);
        DaifugoCard newCard = GameObject.Instantiate<DaifugoCard>(cardBase, cardBase.transform.parent, true);
        cardBase.gameObject.SetActive(false);

        return newCard;
    }


    /// <summary>
    /// é¸æŠä¸­ã®ã‚«ãƒ¼ãƒ‰ã‚’å‡ºã›ã‚‹ã‹
    /// </summary>
    /// <returns></returns>
    bool CheckSelectedCardPlayerble()
    {
        // é¸æŠä¸­ã®ã‚«ãƒ¼ãƒ‰ã¨å½¹ã®å¼·ã•ã‚’åˆ¤å®š
        int selectedCardStrength = 0;
        var selectedCardSetType = DaifugoDefine.CheckCardSetType(_selectedCardList, out  selectedCardStrength);

        // ã‚«ãƒ¼ãƒ‰ã®å½¹ãŒä¸æ­£ãªå ´åˆã¯å‡ºã›ãªã„
        if(selectedCardSetType == DaifugoDefine.eCardSetType.None || selectedCardSetType == DaifugoDefine.eCardSetType.Illegal)
        {
            return false;
        }

        // ã‚«ãƒ¼ãƒ‰ãŒå‡ºã•ã‚Œã¦ã„ãªã„å ´åˆã¯å‡ºã›ã‚‹
        if(_topcardList.Count == 0)
        {
            return true;
        }

        // ã‚«ãƒ¼ãƒ‰ã®æšæ•°ãŒç•°ãªã‚‹
        if(_selectedCardList.Count != _topcardList.Count)
        {
            return false;
        }

        // å‡ºã•ã‚Œã¦ã„ã‚‹ã‚«ãƒ¼ãƒ‰ã®å½¹ã¨å¼·ã•ã‚’åˆ¤å®š
        int topCardStrength;
        var topCardSetType = DaifugoDefine.CheckCardSetType(_selectedCardList, out topCardStrength);

        // ã‚«ãƒ¼ãƒ‰ã®å½¢å¼ãŒç•°ãªã‚‹å ´åˆã¯å‡ºã›ãªã„
        if(selectedCardSetType != topCardSetType)
        {
            return false;
        }

        // ã‚«ãƒ¼ãƒ‰ã®å¼·ã•ãŒã†ã‚å¾…ã£ã¦ã„ãŸã‚‰å‡ºã›ã‚‹
        if(selectedCardStrength > topCardStrength)
        {
            return true;
        }

        return false;

    }
}
